import 'ts-node/register/transpile-only';
import * as fs from 'fs';
import * as path from 'path';

// Preconfigure module aliasing to avoid pulling Hardhat at runtime
// eslint-disable-next-line @typescript-eslint/no-var-requires
const moduleAlias = require('module-alias');
moduleAlias.addAlias('hardhat', 'ethers');

const ROOT = path.resolve(__dirname, '../../../../');
const PKG_ROOT = path.resolve(__dirname, '../..');
const PAYMENT_METHODS_DIR = path.join(PKG_ROOT, 'paymentMethods');

// TypeScript interface for payment method configuration
export interface PaymentMethodConfig {
  paymentMethodHash: string;
  currencies: string[];  // Array of currency hashes
  timestampBuffer: number;  // Always a number in decimal format
  providerHashes: string[];
}

export interface NetworkPaymentMethods {
  network: string;
  chainId?: number | string;
  generatedAt: string;
  methods: Record<string, PaymentMethodConfig>;
}

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

// The package is an active API, so it is generated from an explicit catalog
// rather than copying every immutable entry from deployment history.
const PUBLISHED_PAYMENT_METHOD_NAMES = new Set([
  'alipay',
  'cashapp',
  'chime',
  'mercadopago',
  'mercury',
  'monzo',
  'paypal',
  'revolut',
  'upi',
  'venmo',
  'wise',
  'zelle',
]);

export function renderPaymentMethodsIndex(networks: string[]): string {
  return `// Auto-generated by extract-all.ts
// Unified payment method configurations per network

import type { PaymentMethodConfig, NetworkPaymentMethods } from './types';
${networks.map((network) => `import ${network}Data from './${network}.json';`).join('\n')}
export type { PaymentMethodConfig, NetworkPaymentMethods };

// Network-specific payment method exports
${networks.map((network) => `export { default as ${network} } from './${network}.json';`).join('\n')}

// Cross-network name-to-hash and hash-to-name lookups
export { default as lookups } from './lookups.json';

const paymentMethodsByNetwork: Record<string, NetworkPaymentMethods> = {
${networks.map((network) => `  ${network}: ${network}Data,`).join('\n')}
};

export function getPaymentMethodConfig(
  network: string,
  paymentMethod: string,
): PaymentMethodConfig | undefined {
  return paymentMethodsByNetwork[network]?.methods?.[paymentMethod];
}

export const paymentMethods = paymentMethodsByNetwork;
`;
}

export async function extractPaymentMethods(): Promise<void> {
  ensureDir(PAYMENT_METHODS_DIR);

  // Step 1: Get chainId for each network from deployments/outputs (excluding localhost)
  const outputsDir = path.join(ROOT, 'deployments', 'outputs');
  const chainIdByNetwork: Record<string, number | string> = {};

  if (fs.existsSync(outputsDir)) {
    const contractsFiles = fs.readdirSync(outputsDir).filter(f => f.endsWith('Contracts.ts'));
    for (const file of contractsFiles) {
      try {
        const mod = require(path.join(outputsDir, file));
        const data = mod.default || mod;
        const network = file.replace(/Contracts\.ts$/, '');

        // Skip localhost
        if (network === 'localhost') continue;

        chainIdByNetwork[network] = data.chainId;
      } catch (e) {
        console.warn(`⚠️  Failed to get chainId from ${file}:`, e);
      }
    }
  }

  // Step 2: Load provider data from deployments/outputs/platforms (excluding localhost)
  // This now includes currencies and timestampBuffer from deployment snapshots
  const platformsDir = path.join(ROOT, 'deployments', 'outputs', 'platforms');

  if (!fs.existsSync(platformsDir)) {
    console.warn('⚠️  No provider hashes found at deployments/outputs/platforms');
    return;
  }

  const providerFiles = fs.readdirSync(platformsDir)
    .filter(f => f.endsWith('.json') && f !== 'localhost.json'); // Exclude localhost

  const networks: string[] = [];

  // Step 3: Create unified payment method configs per network
  for (const file of providerFiles) {
    try {
      const network = file.replace('.json', '');
      const providerData = JSON.parse(fs.readFileSync(path.join(platformsDir, file), 'utf8'));
      const methods = providerData.methods || {};

      // Build network payment methods config
      const networkConfig: NetworkPaymentMethods = {
        network,
        chainId: chainIdByNetwork[network],
        generatedAt: new Date().toISOString(),
        methods: {}
      };

      // Process each payment method
      for (const [methodKey, entry] of Object.entries<any>(methods)) {
        if (!PUBLISHED_PAYMENT_METHOD_NAMES.has(methodKey)) continue;

        const paymentMethodHash = entry.paymentMethodHash?.toLowerCase?.() || '';
        // Read currencies and timestampBuffer directly from the snapshot
        const currencies = entry.currencies || [];
        const timestampBuffer = entry.timestampBuffer || 30;
        const providerHashes = (entry.hashes || []).map((h: string) => h.toLowerCase());

        networkConfig.methods[methodKey] = {
          paymentMethodHash,
          currencies,
          timestampBuffer, // Now always a number from snapshot
          providerHashes
        };
      }

      // Write network-specific payment methods file
      const normalizedNetworkName = network.replace(/_([a-z])/g, (_, char) => char.toUpperCase());
      const outPath = path.join(PAYMENT_METHODS_DIR, `${normalizedNetworkName}.json`);
      fs.writeFileSync(outPath, JSON.stringify(networkConfig, null, 2));
      networks.push(normalizedNetworkName);

      // Write per-network .d.ts alongside JSON for strong typing
      const perNetworkDts = `// Typed payment methods file for ${normalizedNetworkName}
export type PaymentMethods = { methods: Record<string, { paymentMethodHash?: \`0x\${string}\`; currencies?: string[] }> };
declare const value: PaymentMethods;
export default value;
`;
      fs.writeFileSync(path.join(PAYMENT_METHODS_DIR, `${normalizedNetworkName}.d.ts`), perNetworkDts);

    } catch (e) {
      console.warn(`⚠️  Failed to process provider file ${file}:`, e);
    }
  }

  // Step 4: Create index with metadata
  const indexJson = {
    networks,
    generatedAt: new Date().toISOString()
  };
  fs.writeFileSync(path.join(PAYMENT_METHODS_DIR, 'index.json'), JSON.stringify(indexJson, null, 2));

  // Step 5: Create TypeScript type definitions
  const typesContent = `// Auto-generated type definitions for payment method configurations

export interface PaymentMethodConfig {
  paymentMethodHash: string;
  currencies: string[];  // Array of currency hashes
  timestampBuffer: number;  // Always a number in decimal format
  providerHashes: string[];
}

export interface NetworkPaymentMethods {
  network: string;
  chainId?: number | string;
  generatedAt: string;
  methods: Record<string, PaymentMethodConfig>;
}
`;
  fs.writeFileSync(path.join(PAYMENT_METHODS_DIR, 'types.d.ts'), typesContent);

  // Step 6: Create TypeScript index
  const indexContent = renderPaymentMethodsIndex(networks);

  fs.writeFileSync(path.join(PAYMENT_METHODS_DIR, 'index.ts'), indexContent);

  // Also write an index.d.ts so exports can reference it
  const indexDts = `// Typed re-exports for payment methods\n${networks.map(net => `export { default as ${net} } from './${net}';`).join('\n')}\nexport { default as lookups } from './lookups';\n`;
  fs.writeFileSync(path.join(PAYMENT_METHODS_DIR, 'index.d.ts'), indexDts);

  // Step 7: Generate lookups.json with cross-network name<->hash mappings
  const nameToHash: Record<string, string> = {};
  const hashToName: Record<string, string> = {};

  // Read back all per-network JSON files and merge method entries
  for (const net of networks) {
    try {
      const netData = JSON.parse(
        fs.readFileSync(path.join(PAYMENT_METHODS_DIR, `${net}.json`), 'utf8')
      );
      for (const [methodName, config] of Object.entries<any>(netData.methods)) {
        const hash = config.paymentMethodHash?.toLowerCase();
        if (hash && !nameToHash[methodName]) {
          nameToHash[methodName] = hash;
          hashToName[hash] = methodName;

        }
      }
    } catch (e) {
      console.warn(`⚠️  Failed to read back ${net}.json for lookups:`, e);
    }
  }

  // Retired on-chain payment methods (removed from the active PaymentVerifierRegistry
  // via governance, e.g. n26 / luxon). Their payment-method hashes are immutable
  // on-chain history, so we keep them resolvable for LABELING ONLY: historical
  // deposits / intents / stats must still render the correct platform name long after
  // the method leaves the active registry. They are added to hashToName but NOT
  // nameToHash — offering/eligibility is gated at the product layer (curator), and
  // leaving them out of nameToHash keeps them unselectable for new liquidity.
  const RETIRED_METHOD_HASH_TO_NAME: Record<string, string> = {
    '0xd9ff4fd6b39a3e3dd43c41d05662a5547de4a878bc97a65bcb352ade493cdc6b': 'n26',
    '0xaea63ef983458674f54ee50cdaa7b09d80a5c6c03ed505f51c90b0f2b54abb01': 'luxon',
  };
  for (const [hash, name] of Object.entries(RETIRED_METHOD_HASH_TO_NAME)) {
    const normalized = hash.toLowerCase();
    if (!hashToName[normalized]) {
      hashToName[normalized] = name;
    }
  }

  const lookupsJson = {
    generatedAt: new Date().toISOString(),
    nameToHash,
    hashToName
  };

  fs.writeFileSync(
    path.join(PAYMENT_METHODS_DIR, 'lookups.json'),
    JSON.stringify(lookupsJson, null, 2)
  );

  // Write lookups.d.ts for the JSON file
  const lookupsDts = `// Typed lookups file for payment methods
export type PaymentMethodLookups = {
  generatedAt: string;
  nameToHash: Record<string, string>;
  hashToName: Record<string, string>;
};
declare const value: PaymentMethodLookups;
export default value;
`;
  fs.writeFileSync(path.join(PAYMENT_METHODS_DIR, 'lookups.d.ts'), lookupsDts);

  console.log(`✅ Unified payment method configs written to ${PAYMENT_METHODS_DIR}`);
}
