name: Foundry Tests
on: [push]

jobs:
  foundry-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: |
          yarn install
          forge --version

      - name: Run Foundry unit tests
        run: |
          echo "Running unit tests..."
          forge test --match-path "test-foundry/unit/*.t.sol" -vv

      - name: Run Foundry fuzz tests
        run: |
          echo "Running fuzz tests..."
          FOUNDRY_FUZZ_RUNS=100 forge test --match-contract "Fuzz" -vv

      - name: Run Foundry invariant tests
        run: |
          echo "Running invariant tests..."
          forge test --match-contract "Invariant" -vv

  foundry-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: yarn install

      - name: Run Foundry coverage (lcov)
        run: forge coverage --report lcov

      - name: Upload Foundry coverage to Codecov (non-blocking)
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          flags: foundry
          name: foundry-coverage
          fail_ci_if_error: false

  
