name: Foundry Tests
on: [push, pull_request]

jobs:
  foundry-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit, fuzz, invariant, critical]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: |
          yarn install
          forge --version

      - name: Run unit tests
        if: matrix.test-type == 'unit'
        run: forge test --match-test "^test[^_]" -vv

      - name: Run fuzz tests
        if: matrix.test-type == 'fuzz'
        run: FOUNDRY_FUZZ_RUNS=1000 forge test --match-contract "Fuzz" -vv

      - name: Run invariant tests
        if: matrix.test-type == 'invariant'
        run: forge test --match-contract "Invariant" -vv

      - name: Run critical path tests
        if: matrix.test-type == 'critical'
        run: FOUNDRY_FUZZ_RUNS=100 forge test --match-contract "CriticalPathFuzz" -vv

  foundry-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: yarn install

      - name: Run coverage
        run: forge coverage --report lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          flags: foundry
          name: foundry-coverage